In [ ]:
from google.colab import files
uploaded = files.upload()

import io

Saving preprocessed_data.csv to preprocessed_data.csv


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

class MyLinearRegression:
    def __init__(self):
        self.df = pd.read_csv('preprocessed_data.csv', names=['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','target'])
        self.df.head()
        
    def processedData(self):
        # clean data
        #for cat in ['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','target']:
            #if self.df[self.df[cat]== '?'].empty == False:
                #print(self.df[self.df[cat]== '?'])
                
        # Remove columns with missing data
        for cat in self.df:
            if self.df[self.df[cat] == '?'].empty == True: # if there is no missing value in a single category, then pass
                pass
            else:
                self.df.drop(self.df[self.df[cat] == '?'].index, inplace=True) # drop the row with missing data
        self.df['ca'] = self.df['ca'].astype('float64')
        self.df['thal'] = self.df['thal'].astype('float64')
        self.df.shape
        
        # lists of categorical attributes and numerical attributes
        cat_att = ['age', 'sex','cp', 'fbs', 'restecg', 'exang', 'slope', 'thal']
        num_att = ['trestbps','chol','thalach','oldpeak','ca']
        
        df_log = self.df.copy()
        df_log['trestbps']=np.log(df_log['trestbps'])
        df_log['chol']=np.log(df_log['chol'])
        df_log['thalach']=np.log(df_log['thalach'])
        
        #normalize
        df_norm = self.df.copy()
        scaler = MinMaxScaler()
        for cat in df_norm.columns:
            if df_norm[cat].dtype == 'int64' or df_norm[cat].dtype == 'float64':
                df_norm[cat]= scaler.fit_transform(df_norm[cat].values.reshape(-1,1))
        df_norm.head()
        
        #X = self.df[['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']]
        #y = self.df['target']
        #X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
        #X_train.head()
        #print(self.df)
        return self.df

    # this function is from hw2 sol
    def mse(self,y,prediction):
        s = 0
        for i in range(len(y)):
            s+=(y[i]-prediction[i])**2
        score = s/len(y)
        return score
    
    
    def fit_predict(self):
        train, test = train_test_split(df_clean, train_size=0.7, random_state=42)
        
        train_x = np.array(train_data[['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']])
        test_x = np.array(test_data[['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']])
        train_y = np.array(train_data['target'])
        test_y = np.array(test_data['target'])
        
        lr = LinearRegression()
        lr.fit(train.drop[''], train_y)
        
        y_test_prediction = lr.predict(test_x)
        print("predicted vals: \n", y_test_prediction, "\n")
        mse = self.mse(test_y, y_test_prediction)
        print("mse: ", mse, "\n")
        
        print("predicted value for user input:", lr.predict(np.array([[63,1,1,145,233,1,2,150,0,2.3,3,0,6]])), "\n")
        
        df = pd.DataFrame({'Actual': test_y, 'Predicted': y_test_prediction})
        print(df)
    
        
def main():
    lr = MyLinearRegression()
#     lr.processedData()
#     lr.fit_predict()
    
main()

In [ ]:
# Logistic Regression

In [ ]:
from sklearn import linear_model
logr = linear_model.LogisticRegression(n_jobs =-1,solver = 'lbfgs', max_iter=500)

In [ ]:
df = pd.read_csv(io.StringIO(uploaded['preprocessed_data.csv'].decode('utf-8')))

df = df.iloc[1:]

In [ ]:
# Split dataset

y = df['target']
X = df[['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']]

X_train = X[89:]
X_test = X[:89]
y_train = y[89:]
y_test = y[:89]

In [ ]:
# Recall Score

logr.fit(X_train,y_train)

y_pred = logr.predict(X_test)
y_true = y_test.values.tolist()

rec_logr = recall_score(y_true, y_pred, average='macro')

print("The recall score of this model is: ", rec_logr)

The recall score of this model is:  0.3237777777777778


In [ ]:
np.sum(logr.predict_proba(X_train),axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
logr.predict(X_train)

array([3, 2, 0, 0, 1, 3, 3, 0, 0, 0, 0, 0, 0, 3, 0, 1, 0, 2, 0, 0, 0, 0,
       2, 2, 0, 0, 0, 3, 3, 3, 2, 0, 2, 0, 0, 3, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 1, 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 3, 3, 0,
       1, 3, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0, 3, 2, 3, 3, 0, 0,
       0, 3, 0, 1, 0, 0, 0, 1, 1, 3, 0, 3, 2, 0, 3, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 3, 3, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 1, 0, 0, 1, 3, 0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       1, 2, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 2, 0, 0,
       3, 1, 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 3, 0, 0, 3, 3, 0, 0, 0, 0, 3,
       3, 0, 0, 3, 1, 0, 2, 3, 0])

In [ ]:
np.unique(y_train)

array([0, 1, 2, 3, 4])

In [ ]:
# Precision Score
from sklearn.metrics import accuracy_score

acc_logr = accuracy_score(y_true, y_pred)
print("The accuracy of this model is: ", acc_logr)

The accuracy of this model is:  0.6179775280898876


In [ ]:
# Accuracy Score
from sklearn.metrics import precision_score

prec_logr = precision_score(y_true, y_pred, average='macro')
print("The precision score of this model is: ", prec_logr)

The precision score of this model is:  0.32645833333333335


## Logistic Regression with L1 Penalty

In [ ]:
# logistic regression with L1 penalty
from sklearn.linear_model import LogisticRegression
lrg_l1 = LogisticRegressionCV(penalty='l1', solver='saga',cv=3,
                              scoring='accuracy', random_state=0,max_iter =8000)
lrg_l1.fit(X_train, y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=3, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=8000, multi_class='auto', n_jobs=None,
                     penalty='l1', random_state=0, refit=True,
                     scoring='accuracy', solver='saga', tol=0.0001, verbose=0)

In [ ]:
# Accuracy Score
acc_lrg_l1 = lrg_l1.score(X_test,y_test)
print("The precision score of this model is: ", acc_lrg_l1)

The precision score of this model is:  0.5955056179775281


In [ ]:
# Recall Score

y_pred_l1 = lrg_l1.predict(X_test)
y_true = y_test.values.tolist()

rec_lrg_l1 = recall_score(y_true, y_pred_l1, average='macro')

print("The recall score of this model is: ", rec_lrg_l1)

The recall score of this model is:  0.2611111111111111


In [ ]:
# Precision Score

prec_lrg_l1 = precision_score(y_true, y_pred_l1, average='macro')
print("The precision score of this model is: ", prec_lrg_l1)


The precision score of this model is:  0.2401656314699793


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Logistic Regression with L2 Penalty

In [ ]:
# logistic regression with L2 penalty
from sklearn.linear_model import LogisticRegressionCV
lrg_l2 = LogisticRegressionCV(penalty='l2', solver='newton-cg', cv=3, 
                              scoring = 'accuracy', random_state=0,max_iter =2000)
lrg_l2.fit(X_train, y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=3, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=2000, multi_class='auto', n_jobs=None,
                     penalty='l2', random_state=0, refit=True,
                     scoring='accuracy', solver='newton-cg', tol=0.0001,
                     verbose=0)

In [ ]:
# Accuracy Score
acc_lrg_l2 = lrg_l2.score(X_test,y_test)
print("The precision score of this model is: ", acc_lrg_l2)

The precision score of this model is:  0.6179775280898876


In [ ]:
# Recall Score

y_pred_l2 = lrg_l2.predict(X_test)
y_true = y_test.values.tolist()

rec_lrg_l2 = recall_score(y_true, y_pred_l2, average='macro')

print("The recall score of this model is: ", rec_lrg_l2)

The recall score of this model is:  0.3055555555555555


In [ ]:
# Precision Score

prec_lrg_l2 = precision_score(y_true, y_pred_l2, average='macro')
print("The precision score of this model is: ", prec_lrg_l2)

The precision score of this model is:  0.3244947209653092


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import numpy as np

In [ ]:
df.head()

age  sex   cp  trestbps   chol  ...  oldpeak  slope   ca  thal  target
1  67.0  1.0  4.0     160.0  286.0  ...      1.5    2.0  3.0   3.0       2
2  67.0  1.0  4.0     120.0  229.0  ...      2.6    2.0  2.0   7.0       1
3  37.0  1.0  3.0     130.0  250.0  ...      3.5    3.0  0.0   3.0       0
4  41.0  0.0  2.0     130.0  204.0  ...      1.4    1.0  0.0   3.0       0
5  56.0  1.0  2.0     120.0  236.0  ...      0.8    1.0  0.0   3.0       0

[5 rows x 14 columns]

In [ ]:
# Input data to predict

age = input("Enter your age: ")
sex = input("Enter your sex: ")
cp = input("Enter your cp: ")
trestbps = input("Enter your trestbps: ")
chol = input("Enter your chol: ")
fbs = input("Enter your fbs: ")
restecg = input("Enter your restecg: ")
thalach = input("Enter your thalach: ")
exang = input("Enter your exang: ")
oldpeak  = float(input("Enter your oldpeak: "))
slope  = input("Enter your slope: ")
ca  = input("Enter your ca: ")
thal  = input("Enter your thal: ")

logr.fit(X,y)
const = [age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal]
const = np.array(const, dtype=np.float64)
target = logr.predict([const])
# target = logr.predict([[63,1,1,145,233,1,2,150,0,2.3,3,0,6]])
print(target)


KeyboardInterrupt: ignored